import { access, stat } from 'node:fs/promises'
import { constants } from 'node:fs'
import { dirname, isAbsolute, join, resolve, delimiter, extname } from 'node:path'
import type { CodingExecutor } from '@ai-council/coding'
import type { CommandSpec } from '@ai-council/project-domain'

export class PreflightError extends Error {
  constructor(public readonly issues: string[]) {
    super(`Startprüfung fehlgeschlagen:\n${issues.map(issue => `• ${issue}`).join('\n')}`)
  }
}

/** Resolve only; never execute an arbitrary configured test command as a probe. */
export async function findExecutable(command: string, cwd: string, environment = process.env, platform = process.platform): Promise<string | undefined> {
  if (!command.trim()) return undefined
  const windows = platform === 'win32'
  const pathValue = Object.entries(environment).find(([key]) => key.toLowerCase() === 'path')?.[1] ?? ''
  const pathExt = Object.entries(environment).find(([key]) => key.toLowerCase() === 'pathext')?.[1] ?? '.COM;.EXE;.BAT;.CMD'
  const extensions = windows ? pathExt.split(';').filter(Boolean) : ['']
  const hasPath = isAbsolute(command) || /[\\/]/.test(command)
  const roots = hasPath ? [''] : windows ? [cwd, ...pathValue.split(';')] : pathValue.split(delimiter)
  for (const root of roots) {
    const candidate = hasPath ? resolve(cwd, command) : resolve(root.replace(/^"|"$/g, '') || cwd, command)
    const suffixes = !windows || extensions.some(ext => ext.toLowerCase() === extname(candidate).toLowerCase()) ? [''] : extensions
    for (const suffix of suffixes) {
      const file = candidate + suffix
      try {
        if (!(await stat(file)).isFile()) continue
        await access(file, windows ? constants.F_OK : constants.X_OK)
        return file
      } catch { /* try next PATH entry */ }
    }
  }
  return undefined
}

export async function directoryIssues(directory: string | undefined, allowCreate: boolean, writable = true): Promise<string[]> {
  if (!directory || !isAbsolute(directory)) return ['Einen absoluten Projektordner auswählen.']
  let candidate = directory
  for (;;) {
    try {
      if (!(await stat(candidate)).isDirectory()) return [`${candidate} ist kein Ordner. Einen gültigen Projektordner auswählen.`]
      await access(candidate, constants.R_OK | (writable ? constants.W_OK : 0))
      return []
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT' && allowCreate && dirname(candidate) !== candidate) {
        candidate = dirname(candidate)
        continue
      }
      return [`Projektordner ${directory} ist nicht ${writable ? 'les- und schreibbar' : 'lesbar'}. Pfad und Zugriffsrechte prüfen.`]
    }
  }
}

export async function executionPreflight(directory: string | undefined, commands: CommandSpec[], executors: CodingExecutor[], allowCreate = true, writable = true): Promise<void> {
  const issues = await directoryIssues(directory, allowCreate, writable)
  const cwd = directory && isAbsolute(directory) ? directory : process.cwd()
  for (const executable of new Set(['git', ...commands.map(command => command.executable)])) {
    // Project-local tools may be generated by an implementation or dependency install.
    // Still report their absence early when the user explicitly configured them.
    if (!await findExecutable(executable, cwd)) issues.push(`Werkzeug „${executable}“ fehlt oder ist nicht ausführbar. Installieren/PATH prüfen oder den Befehl im Prüfprofil korrigieren.`)
  }
  const detected = await Promise.allSettled([...new Set(executors)].map(async executor => {
    const availability = await executor.detect()
    if (!availability.installed) return `Agent „${executor.id}“ ist nicht installiert. Unter Einstellungen → Coding-Agenten prüfen.`
    if (availability.authStatus === 'unauthenticated') return `Agent „${executor.id}“ ist nicht angemeldet. Anmeldung im Agenten durchführen und unter Einstellungen erneut prüfen.`
    return undefined
  }))
  detected.forEach(result => {
    if (result.status === 'rejected') issues.push(`Agent konnte nicht geprüft werden: ${result.reason instanceof Error ? result.reason.message : String(result.reason)}`)
    else if (result.value) issues.push(result.value)
  })
  if (issues.length) throw new PreflightError(issues)
}
