export const WORKFLOW_GUIDANCE = `Arbeite im Umfang des Nutzerziels. Für kleine Anwendungen wie einen Taschenrechner genügen eine einfache Architektur und wenige zusammenhängende, ausführbare Arbeitspakete inklusive ihrer Tests. Erfinde keine zusätzlichen Produktanforderungen oder separaten Architektur-, Vertrags- und Dokumentationsphasen ohne konkreten Bedarf.
Entscheide reversible Implementierungsdetails selbst anhand bestehender Konventionen. Dokumentiere nötige Standardannahmen kurz in den Architektur-Notizen; fordere dafür keine Einzelbestätigung an. Bereits genehmigte Entscheidungen und explizite Nutzeranforderungen bleiben verbindlich.
Offene Fragen sind nur dann blockierend, wenn ohne die Antwort wesentlich unterschiedliche Produkte entstehen würden, verbindliche Anforderungen widersprüchlich sind oder eine Entscheidung über Kosten, Sicherheit oder externe Auswirkungen fehlt. Formuliere dann die konkrete Entscheidung und eine Empfehlung. Eine fehlende defensive Kopie, Fehlerklassifikation, Bereichsprüfung oder ein fehlender Verhaltenstest ist normalerweise eine Implementierungsaufgabe.`

export function planningGuidance(profile: 'simple' | 'standard'): string {
  return profile === 'simple'
    ? 'Planungsprofil: Einfaches Projekt. Plane möglichst 1–3 nutzbare, durchgängig testbare Funktionen. Beispiel Taschenrechner: Rechnen mit Eingabe, Ergebnis und Fehlerfällen als ein Arbeitspaket; zusätzliche Funktionen nur wenn ausdrücklich verlangt. Infrastruktur, interne Typen, Grammatik und Tests sind Bestandteile dieser Funktionen und keine eigenen Vorabprojekte. Verzichte auf erfundene Architekturpflichten. Falls mehr Aufgaben zwingend nötig sind, begründe dies in den Aufgabenbeschreibungen anhand konkreter Anforderungen. Bestehende genehmigte Anforderungen nicht streichen.'
    : 'Planungsprofil: Größeres Projekt. Schneide nach eigenständig prüfbaren Funktionen und tatsächlichen Abhängigkeiten. Begründe separate Infrastrukturarbeiten durch mehrere konkrete Verbraucher; keine pauschalen Schichten- oder Dokumentationsphasen.'
}
